COVERALLS_PARALLEL=true
language: node_js
node_js:
  - "stable"
install: npm install
cache:
  directories:
    - node_modules
addons:
  postgresql: "9.6"

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE Property_Pro_Lite" -U postgres
  - npm i
  - npm run copytest
env:
  global:
    - DB_TEST="postgres://postgres@localhost/Property_Pro_Lite"
script:
  - npm run test
after_success:
  - npm run coveralls
  
notifications:
email: false
webhooks: https://coveralls.io/webhook?repo_token=X3pf46eLyf48DkaVNLK3d1lLryn1lUkO5

  

